version: '3.7'
services:
  web-explorer:
    build:
      context: ./web
    environment:
      PORT: 3000
    ports:
      - 3000:3000
    command: yarn start
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
      
  api-explorer:
    build:
      context: ./api
    environment:
      PORT: 8081
    ports:
      - 8081:8081
    command: yarn start
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
  